# Generated by Django 3.2.4 on 2021-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0002_auto_20210622_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketer',
            name='cricketer',
        ),
        migrations.AddField(
            model_name='name',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='cricketer',
            field=models.CharField(choices=[('sachin tendulkar', 'sachin tendulkar'), ('Virat kohli', 'virat Kohli'), ('Adam Gilchirst', 'Adam Gilchirst'), ('Jacques Kallis', 'Jacques Kallis')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Cricketer',
        ),
    ]
